kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deployment-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create"]
