FROM golang:1.21 as builder
WORKDIR /src
COPY <<EOF ./main.go
package main

import "fmt"

func main() {
    fmt.Println("hello from Golang!")
}
EOF
RUN go build -o /bin/hello ./main.go

FROM scratch
COPY --from=builder /bin/hello /hello
CMD ["/hello"]
