kind: Pod  
apiVersion: v1  
metadata:
 name: pod-two
 namespace: my-namespace
spec:  
 containers:
   - name: nginx-pod-two
     image: nginx:alpine
     resources:
       requests:
         memory: 512Mi
         cpu: "0.5"
       limits:
         memory: 1024Mi  
         cpu: "2"
