apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  #namespace: default
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-image-tag
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "El uso del tag 'latest' en las imágenes está prohibido."
        pattern:
          spec:
            containers:
              - image: "!*latest"

