apiVersion: v1
kind: Pod
metadata:
  name: test-max-limits
  labels:
    team: backend
spec:
  containers:
  - name: test
    image: busybox:1.33.1
    command: ['sh', '-c', 'while true; do cat /etc/shadow; sleep 5; done']
    resources:
      requests:
        #memory: "200Mi"
        memory: "1025Mi"
        cpu: "0.6"
      limits:
        #memory: "1000Mi"
        memory: "1025Mi"
        cpu: "1"
