apiVersion: v1
kind: Pod
metadata:
  name: test-valid-registry
  labels:
    team: backend
spec:
  containers:
  - name: test
    #image: nginx:alpine
    image: mario21ic/nginx:alpine
    command: ['sh', '-c', 'while true; do cat /etc/shadow; sleep 5; done']
