apiVersion: v1
kind: Pod
metadata:
  name: test-latest
  #labels:
  #  team: backend
spec:
  containers:
  - name: test
    #image: busybox
    image: busybox:latest
    command: ['sh', '-c', 'while true; do cat /etc/shadow; sleep 5; done']
