apiVersion: v1
kind: Pod
metadata:
  name: test-team-label
  #labels:
  #  team: backend
spec:
  containers:
  - name: test
    image: busybox:1.33.1
    command: ['sh', '-c', 'while true; do cat /etc/shadow; sleep 5; done']
