apiVersion: v1
kind: Pod
metadata:
 name: pod-privileged
spec:
 containers:
 - name: sec-ctx-3
   image: ubuntu:22.04
   command: [ "sh", "-c", "sleep 1h" ]
   securityContext:
     privileged: true
     allowPrivilegeEscalation: true
