kind: Pod
apiVersion: v1
metadata:
  name: immutability-pod3
spec:
  hostNetwork: false  # 3. host namespaces puede hacer mutable, ademas de no usar su propia red

  containers:
  - name: nginx
    image: nginx:alpine

    securityContext:
      readOnlyRootFilesystem: true # 1. para que no reescribe el codigo ni nada del FS en runtime

      privileged: false # 2. nunca modo privileged
      allowPrivilegeEscalation: false # no permitir escalamiento
      #runAsUser: 0 # 2. nunca root
      runAsUser: 1000 # 2. poner un usuario o dejar el del image

    volumeMounts: # 1. para poder escribir de forma temporal en carpetas especificas
    - name: cache
      mountPath: /var/cache/nginx
    - name: runtime
      mountPath: /var/run

  volumes: # emptyDirs
  - name: cache
    emptyDir: {}
  - name: runtime
    emptyDir: {}

